project:
  type: book
  output-dir: docs

book:
  title: "Nonlinear mixed-effects modelling with nlmixr2"
  author: 
  - Justin J. Wilkins, Occams
  - Matthew Fidler, Novartis
  
  date: "26/11/2024"
  
  page-footer:
    left: |
      Nonlinear mixed-effects modelling with nlmixr2 was written by Justin Wilkins, Matthew Fidler, 
      William Denney, John Harrold, Richard Hooijmaaijers, Rik 
      Schoemaker and Mirjam Trame.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/kestrel99/nlmixr2_book/
  repo-branch: main
  
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters: 
        - 01_intro.qmd
        - 02_prerequisites.qmd
        - 03_history.qmd
    - part: "Population Pharmacokinetics and Pharmacodynamics"
      chapters: 
        - 04_intro_to_poppkpd.qmd
        - 05_intro_to_nlme.qmd
    - part: "Simulations with `rxode2`"
      chapters: 
        - 06_models.qmd
        - 07_events.qmd
        - 08_single_subjects.qmd
        - 09_populations.qmd
        - 10_more_complex_examples.qmd
    - part: "Data Preparation and Management"
      chapters: 
        - 11_data_structure.qmd
        - 12_exploratory_analysis.qmd
    - part: "Modeling with `nlmixr2`"
      chapters: 
        - 13_parameter_estimation_and_model_fitting.qmd
        - 14_diagnostics_and_evaluation.qmd
        - 15_handling_covariate_effects.qmd
        - 16_model_selection_and_comparison.qmd
        - 17_case_studies_and_practical_applications.qmd
        - 18_tracking_work_with_shinymixr.qmd
    - part: "Advanced topics"
      chapters: 
        - 19_inside_mixrverse.qmd
        - 20_extending_mixrverse.qmd
    - part: "The mixrverse"
      chapters: 
        - 21_qualifying_mixrverse.qmd
        - 22_babelmixr.qmd
        - 23_mixrverse.qmd
    - part: "The future"
      chapters: 
        - 24_future_directions.qmd
        - 25_final_thoughts.qmd
    - function_reference.qmd
    - references.qmd

bibliography: references.bib
csl: vancouver.csl

format:
  html:
    theme: litera 
  pdf:
    documentclass: scrreprt

editor: source

