project:
  type: book

book:
  title: "Nonlinear mixed-effects modelling with nlmixr2"
  author: 
  - Justin J. Wilkins, Occams
  - Matthew Fidler, Novartis
  
  date: "16/11/2022"
  
  page-footer:
    left: |
      Nonlinear mixed-effects modelling with nlmixr2 was written by Justin Wilkins, 
      Matthew Fidler, William Denney, John Harrold, Richard Hooijmaaijers, Rik 
      Schoemaker, Mirjam Trame, Yuan Xiong and Huijuan Xu.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/kestrel99/nlmixr2_book/
  repo-branch: main
  
  chapters:
    - index.qmd
    - intro.qmd
    - history.qmd
    - references.qmd

bibliography: references.bib
csl: vancouver.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

